package com.whatime.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

    private Long id;
    private String uuid;
    private String name;
    private String desc;
    private Long parentId;
    private String parentUuid;
    private String imgUri;
    private Boolean del;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String uuid, String name, String desc, Long parentId, String parentUuid, String imgUri, Boolean del) {
        this.id = id;
        this.uuid = uuid;
        this.name = name;
        this.desc = desc;
        this.parentId = parentId;
        this.parentUuid = parentUuid;
        this.imgUri = imgUri;
        this.del = del;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getParentUuid() {
        return parentUuid;
    }

    public void setParentUuid(String parentUuid) {
        this.parentUuid = parentUuid;
    }

    public String getImgUri() {
        return imgUri;
    }

    public void setImgUri(String imgUri) {
        this.imgUri = imgUri;
    }

    public Boolean getDel() {
        return del;
    }

    public void setDel(Boolean del) {
        this.del = del;
    }

}
