package com.whatime.db;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User implements Serializable{

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Long id;
    private String uuid;
    private Integer authType;
    private Boolean available;
    private String city;
    private Long createTime;
    private String email;
    private String identityCard;
    private Boolean del;
    private String levelUuid;
    private Long loginTime;
    private String mime;
    private String nickName;
    private String password;
    private String phoneInfo;
    private String qq;
    private String realName;
    private String telphone;
    private Long uptTime;
    private String userName;
    private String userphotoUri;
    private Integer sex;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String uuid, Integer authType, Boolean available, String city, Long createTime, String email, String identityCard, Boolean del, String levelUuid, Long loginTime, String mime, String nickName, String password, String phoneInfo, String qq, String realName, String telphone, Long uptTime, String userName, String userphotoUri, Integer sex) {
        this.id = id;
        this.uuid = uuid;
        this.authType = authType;
        this.available = available;
        this.city = city;
        this.createTime = createTime;
        this.email = email;
        this.identityCard = identityCard;
        this.del = del;
        this.levelUuid = levelUuid;
        this.loginTime = loginTime;
        this.mime = mime;
        this.nickName = nickName;
        this.password = password;
        this.phoneInfo = phoneInfo;
        this.qq = qq;
        this.realName = realName;
        this.telphone = telphone;
        this.uptTime = uptTime;
        this.userName = userName;
        this.userphotoUri = userphotoUri;
        this.sex = sex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Integer getAuthType() {
        return authType;
    }

    public void setAuthType(Integer authType) {
        this.authType = authType;
    }

    public Boolean getAvailable() {
        return available;
    }

    public void setAvailable(Boolean available) {
        this.available = available;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIdentityCard() {
        return identityCard;
    }

    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    public Boolean getDel() {
        return del;
    }

    public void setDel(Boolean del) {
        this.del = del;
    }

    public String getLevelUuid() {
        return levelUuid;
    }

    public void setLevelUuid(String levelUuid) {
        this.levelUuid = levelUuid;
    }

    public Long getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    public String getMime() {
        return mime;
    }

    public void setMime(String mime) {
        this.mime = mime;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhoneInfo() {
        return phoneInfo;
    }

    public void setPhoneInfo(String phoneInfo) {
        this.phoneInfo = phoneInfo;
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getTelphone() {
        return telphone;
    }

    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    public Long getUptTime() {
        return uptTime;
    }

    public void setUptTime(Long uptTime) {
        this.uptTime = uptTime;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserphotoUri() {
        return userphotoUri;
    }

    public void setUserphotoUri(String userphotoUri) {
        this.userphotoUri = userphotoUri;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

}
