package com.whatime.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOLIDAY.
 */
public class Holiday {

    private Long id;
    private String uuid;
    private String country;
    private String dayOfYear;
    private String holidayName;
    private String holidayDes;
    private Boolean rest;
    private Boolean alarm;

    public Holiday() {
    }

    public Holiday(Long id) {
        this.id = id;
    }

    public Holiday(Long id, String uuid, String country, String dayOfYear, String holidayName, String holidayDes, Boolean rest, Boolean alarm) {
        this.id = id;
        this.uuid = uuid;
        this.country = country;
        this.dayOfYear = dayOfYear;
        this.holidayName = holidayName;
        this.holidayDes = holidayDes;
        this.rest = rest;
        this.alarm = alarm;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getDayOfYear() {
        return dayOfYear;
    }

    public void setDayOfYear(String dayOfYear) {
        this.dayOfYear = dayOfYear;
    }

    public String getHolidayName() {
        return holidayName;
    }

    public void setHolidayName(String holidayName) {
        this.holidayName = holidayName;
    }

    public String getHolidayDes() {
        return holidayDes;
    }

    public void setHolidayDes(String holidayDes) {
        this.holidayDes = holidayDes;
    }

    public Boolean getRest() {
        return rest;
    }

    public void setRest(Boolean rest) {
        this.rest = rest;
    }

    public Boolean getAlarm() {
        return alarm;
    }

    public void setAlarm(Boolean alarm) {
        this.alarm = alarm;
    }

}
